### ISSUE TITLE
Draft initial candidate reporting examples

### ISSUE THREAD

**Issue by llienfec** [18F/fec-cms#1170]
To help users understand how to report campaign finance transactions, we need to draft the content  portion of the reporting examples (language + images) that will go with the candidate section within Help for Candidates and Committees. 

We already have beautifully designed pages/interactions, and have already identified potential reporting examples to add to the candidate section (#1123).  The modules are currently being added to Wagtail (#1160).  To complete this portion of the larger task, we will draft the language and image content for candidate reporting examples, following the great guidelines that @jameshupp drafted.

## Tasks to completion:
- [x] Pick a smaller subset of examples to start with (work with Jim & @rhoughfec).
- [x] Draft language for that subset of examples
- [x] Draft images for that subset of examples.
- [x] Ask @jameshupp to review to ensure FEC team is on the right track.
- [x] Finalize drafts and add any needed clarifications/lessons learned to reporting example content doc.

**Comment by llienfec** [comment]
Met with @rhoughfec and Jim Jones (amazing team!) to plan work on drafting reporting examples.   We picked the following 5 reporting examples first because the number and size of images would likely vary and we want to try out following the "how to report" content guidelines: 

:lock: https://docs.google.com/spreadsheets/d/1CKeSSyFLO7CswnqWHzlaKSTlUZ5z5VXbOPhiuL9oqkM/edit#gid=0 :lock:

### Initial examples:

1. Individual contributions  (requires 1 part of the schedule page)
2. Best efforts (both form images and legal documentation, also need to figure out if it belongs in # 1 above or as its own page)
3. Conduits (2 sections of the form)
4. Partnership contributions (3 sections of the form)
5. Personal funds loans (requires multiple schedules of the form)

@jenniferthibault and @jameshupp already did great work on a few of these examples in the design phase, and we want to carry that learning over into the initial implementation.

### Next steps:
- @llienfec and @rhoughfec will start drafting language and give Jim info for the form images by Monday
- Jim will begin working on images for the examples on Monday

@jenniferthibault Do you have image standards (dimensions, etc.) that we should follow when we're making the images for the How to Report pages?  Also, Jim had a question about acceptable file sizes.  Thanks for any help and guidance you can pass on to us!

**Comment by jenniferthibault** [comment]
I'll definitely work this guidance into the content guidance doc that James made for these examples, but here's a quick summary:

**Image size:** 
Width: 560px
Height: variable

I'm asking for Christine's help in researching wagtail's image compression to know what to recommend for best resolution and max file size. Will update when I know more!

**Comment by jenniferthibault** [comment]
### Image recommendations:

**Filing example images:**
Width: 560px
Height: variable
Recommended maximum file size: 600KB

<img width="736" alt="screen shot 2017-08-07 at 8 53 16 am" src="https://user-images.githubusercontent.com/11636908/29027257-e7a1e264-7b4d-11e7-9a67-056457239d45.png">

**Example scenario headshots**
Width: 60px
Height: 60px

<img width="554" alt="screen shot 2017-08-07 at 8 53 35 am" src="https://user-images.githubusercontent.com/11636908/29027306-1eb239de-7b4e-11e7-9b87-7bc24f343982.png">


I've also integrated this guidance into the [Managing reporting examples](https://docs.google.com/a/gsa.gov/document/d/1Y4qshPcm6eelxqYY_FaxLVE6rLUeZUIsd0N2VlMxzBc/edit?usp=sharing) 🔒 doc.

cc @jjones0618

**Comment by llienfec** [comment]
The awesome @rhoughfec started our [Draft Reporting Scenarios](https://docs.google.com/spreadsheets/d/1lZIuuC4hHL_L3VHO5PcH8HWML7ESZntEVqw61eU7LQI/edit?usp=sharing) :lock: spreadsheet.

**Comment by rhoughfec** [comment]
draft images completed (thanks @jjones0618) . Will share with @jameshupp and @jenniferthibault soon.

**Comment by jenniferthibault** [comment]
Are the images in the file there complete with content, but still awaiting the most recent styling (with the brighter orange highlight and sans serif text to match FEC File) ? Not sure if we should track that criteria here or somewhere else, but want to make sure we don't lose the choice of styling we went with.

**Comment by llienfec** [comment]
Nope, they're not final images.  I noted it in the doc, but should have put it in the issue too!  We have highlighting and font changes discussed last week that need to be implemented as well as some data changes.  I'm going to send all of that @jjones0618 's way after we have edits from James.

**Comment by jjones0618** [comment]
Should we modify the images to match Jen's update or are we waiting for the results of @patphongs's user testing in Chicago later this month?

**Comment by jenniferthibault** [comment]
Ah thanks Lauren!

Let's go with the update so that we can start putting these on the site and will have something live to test in Chicago.

**Comment by llienfec** [comment]
We're going to modify the images at the same time we work on comments on the draft.  That way if anything changes in the reporting examples, Jim can make those edits in addition to the design edits.  We need to figure out overall what's working and what needs to be changed.

**Comment by jjones0618** [comment]
Cool. So we're going with Helvetica to match FECfile, yes?

**Comment by llienfec** [comment]
Awesome.  So we'll plan to get some comments and then move forward with finalizing language, explanations, and images.  We'll have everything in the most up-to-date version in time for Chicago -- really probably within the next few days.

Also, we had talked about having Pat test some of the highlighting options in Chicago, so I'll get in touch with her to see what she would need for testing.
