### ISSUE TITLE
Draft SSF registration content and submit for review

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#123]
**[Story](https://18f.storiesonboard.com/m/fec/!card/i5XjNYkEU7LfGjnT8EgiIg):** So that SSFs can register, they need to find content about the registration process that applies to them.

**Tasks:**
- [x] Do rough outline of what should be included
- [x] Check with Amys
- [x] Draft content
- [x] Submit content for review
- [ ] OGC review
