### ISSUE TITLE
Draft content for SSF registration checklist and submit for review

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#124]
**[Story 1](https://18f.storiesonboard.com/m/fec/!card/3bYlbVFfJzzYpznT8EgiIg)** 
**[Story 2](https://18f.storiesonboard.com/m/fec/!card/gCSRHfjPWegOKjnT8EgiIg)**

So that novice corporations and labor organizations have a clear understanding of what they need to do to register and report as an SSF.

- [x] Draft outline of checklist
- [x] Draft registration content
- [x] Submit registration content for review
- [x] Draft reporting content
- [x] Submit reporting content for review
- [x] Implement edits
- [x] Submit for OGC review
