### ISSUE TITLE
Candidate reporting examples - Disbursements #1

### ISSUE THREAD

**Issue by llienfec** [18F/fec-cms#1379]
To help users understand how to report campaign finance transactions, we need to continue drafting the content portion of the reporting examples (language + images) that will go with the candidate section within Help for Candidates and Committees.

### Background tasks:
- [x] Conduct light research regarding fuzzy images in Wagtail
- [x] Figure out how to use password protected Wagtail pages (dropping for now)

### Tasks to completion:
- [x] Identify 10 examples to create in this sprint
- [x] Write example text, find Getting Started Guide pages and video links  @llienfec
- [x] Compile text for images @rhoughfec
- [x] Create images & review @jjones0618
- [x] Team edit and revisions
- [x] RAD SME review
- [x] Enter into Wagtail
- [x] Publish examples, create links on Filing Reports page
- [ ] Add cards to content pages

**Comment by llienfec** [comment]
Team met today to coordinate work and conduct initial grooming on this issue, to get it ready for next sprint.  We can recalibrate after grooming on Thursday if needed.

### Research
Re: fuzzy images in Wagtail, we may have an issue submitted by Jim on this topic.  We were hoping that there was an easy fix that we could implement without support or something we were doing on our end to cause this.  However, from a quick google search, everything surrounding images looks pretty technical, so we're setting the issue aside for when we have front end help and will proceed like we have been.  http://docs.wagtail.io/en/v1.13/topics/images.html

Played around with Wagtail a little and can't figure out how to put a draft page behind a password.  We used to review content this way, but we may be limited with the move to cloud.gov.

### List of reporting examples
Capping at 10 for this sprint and seeing how that works.  Finishing receipts and starting disbursements with the most common disbursements that candidate committees make:
- Redesignation/reattribution
- Joint fundraising receipts
- Bitcoins
- Offsets to operating expenditures
- Operating expenditures
- Credit card disbursement
- Staff reimbursement
- Travel disbursement
- Refunds
- Charitable donation

**Comment by llienfec** [comment]
Finished drafting reporting example language for:

- Credit card disbursement
- Staff reimbursement
- Travel disbursement
- Refunds
- Charitable donation

**Comment by llienfec** [comment]
Finished the rest of the reporting examples and sent to RAD SME for review - FYI: SME is out of town until Wednesday.

**Comment by llienfec** [comment]
Drafts of all 10 examples are entered in Wagtail.

**Comment by llienfec** [comment]
All RAD SME edits are entered into the wagtail pages.  All we need to do is add images and image descriptions.

**Comment by llienfec** [comment]
We just need 2 pic edits.  All of the wagtail pages are up-to-date and all published except travel reimbursements and refunds.  Did not publish "Filing candidate reports" page yet until those two pics are replaced.  Looking to publish on Monday morning.

**Comment by llienfec** [comment]
Reporting examples are published and available through the "Filing candidate reports" page. The only think left is to insert the reporting example cards into content pages.  

@dorothyyeager and I are going to pair on separating out the content using HTML.  As I understand it, if we use the Wagtail interface, it messes up the HTML for glossary pages.

**Comment by llienfec** [comment]
When we add reporting examples to existing content pages, we have to break up the longer parts into separate sections.  If you copy and paste existing text into a new section using the wagtail interface, the HTML code for the glossary pages does not copy over as well.

To make new sections, you must open the HTML, cut/copy the code, create a new section using the + sign of the wagtail interface, select paragraph, open the HTML editor, and paste the code.  I'll enter a new issue to see if we can get this fixed.

**Comment by llienfec** [comment]
This set of 10 reporting examples has been posted, linked in the Reporting Examples section of the "Filing candidate reports" page, and "how to report..." cards have been added to the content text.  This issue is finished.  

Huge thanks to @rhoughfec and @jjones0618 for all of their amazing work on these examples!  Also to @dorothyyeager for help with the HTML process at the end!
