### ISSUE TITLE
Library content migration

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#404]
# Background
The first wave of migration from FEC.gov to betaFEC will be our proposed `Library` section.

<img width="677" alt="screen shot 2016-07-26 at 2 25 00 pm" src="https://cloud.githubusercontent.com/assets/10552702/17156498/052a2266-533f-11e6-804c-e956a01af8d3.png">

In this initial library migration we are moving:
- FEC Record
- Press releases
- Weekly Digests
- Tips for Treasurers

Those pieces of content exist as a mix of PDF and HTML pages. For this migration:
- Content that exists **only** as a PDF will migrate to betaFEC **as a PDF**.
- Content that exists as a PDF **and** HTML will migrate to betaFEC **as HTML only** (supplementary PDFs will go away).

# Tasks

Tasks needed to complete this first migration wave:
- [x] Complete [content inventory](https://docs.google.com/spreadsheets/d/1LenmU9GkuHgQJPbvf60MIpxxLZ0GvU_TSJkkkF_sAWU/edit)
- [x] Identify content types (https://github.com/18F/fec-cms/issues/392)
 - Create a library landing page
     - [ ] Visual design of library landing page (https://github.com/18F/fec-cms/issues/410)
     - [ ] Content design of library landing page (https://github.com/18F/fec-cms/issues/409)
     - [ ] Implementation 
 - Create a subpages each for FEC Record, press releases, Weekly Digests and Tips for Treasurers
     - [ ] Visual design of subpages (https://github.com/18F/fec-cms/issues/410)
     - [ ] Content design of subpages (https://github.com/18F/fec-cms/issues/409)
     - [ ] Implementation 
 - Migrate the full archive of individual pages (PDF or HTML) onto subpages for FEC Record, press releases, Weekly Digests and Tips for Treasurers
     - [ ] HTML page migration (https://github.com/18F/fec-cms/issues/411)
     - [ ] PDF page migration (https://github.com/18F/fec-cms/issues/412)

Related (and important, but not 100% necessary to complete this wave of migration): https://github.com/18F/fec-cms/issues/403

**Comment by emileighoutlaw** [comment]
cc @amypike @amykort @patphongs — here's our main issue for tracking the first wave of content migration. I spent some time updating it today so that we have a clear picture of what tasks we need to complete. 

One thing we can think about and talk through when we meet next is that a lot of the initial content work is completed. What that means is that the next round of tasks rely on the work of our developers (like Lindsay) and our designers (like Jen), who also have other project work to prioritize. So maybe we can strategize about that. 

This is a lot of stuff to look at and take in. And I think this is the first time we've had it all collected in one central issue. So as you're making your way through this, please let me know if anything in these migration issues are unclear.

**Comment by noahmanger** [comment]
The tasks here are contained in other issues, so I'm going to close.
