### ISSUE TITLE
Content migration: migration of HTML pages to Library

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#411]
This is a sub-task of: https://github.com/18F/fec-cms/issues/404

# Background
In this first wave of content migration we are moving:
- FEC Record
- Press releases
- Weekly Digests
- Tips for Treasurers

Those pieces of content exist as a mix of PDF and HTML pages. This issue focuses specifically on the tasks we need to complete to migrate HTML pages. 

# Tasks
To complete the migration of HTML pages to the Library, we need to do the following:

- Build library templates for Wagtail
    - [x] Jen will open a GitHub issue and (when she’s available) will start designing prototypes for FEC Record, news releases, Weekly Digests, and Tips for Treasurers. 
    - [x] Emileigh and @LindsayYoung will outsource the Wagtail development of those prototypes using micropurchase.

- Migration
    - [x] Lindsay is exploring if there’s a less labor-intensive way to move HTML content into our new templates (i.e., hopefully not one page at a time and by hand). 
    - [ ] Review of pages before they go live (Emileigh and Jeannine can do this; we can also pull in FEC people to help move this along quickly, if they have the capacity)

**Comment by noahmanger** [comment]
Does this need to be it's own issue? Or is this work captured elsewhere?

**Comment by emileighoutlaw** [comment]
Captured elsewhere. Let's close!
