### ISSUE TITLE
Content migration: migration of PDF pages to Library

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#412]
# Background
In this first wave of content migration we are moving:
- Press releases
- Weekly Digests

Those pieces of content exist as a mix of PDF and HTML pages. This issue focuses specifically on the tasks we need to complete to migrate PDF pages. 

# Tasks
To complete the migration of PDF pages to the Library, we need to do the following:

- [x] Identify what the PDF pages need to move to the Library (sent to Pat)
- [x] Decide how and where to store PDFs. After an initial discussion with Lindsay and Pat, it seems like AWS might be the best option.
- [x] When PDFs are moved to their new home, link to those PDFs from our library subpages. 
- [ ] Map and redirect FEC.gov PDF pages to betaFEC PDF pages.

cc @patphongs

**Comment by emileighoutlaw** [comment]
This is actually done, right, @LindsayYoung ? Can we close?

**Comment by emileighoutlaw** [comment]
Keeping this issue open until @patphongs confirms that this is done and we can close.

Pat— let us know if you need any help on this?
