### ISSUE TITLE
Home page user research synthesis

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#463]
Step 1 of our [home page plan](https://github.com/18F/fec-cms/issues/432) involves various types of research. This issue captures the task of synthesizing prior user research:

- What do we currently know about user needs and priorities for fec.gov and what does that tell us about what the home page should do?

**Tasks:**
- [ ] Create a re-consolidated, re-synthesized understanding of user needs/priorities, and areas for further research
- [ ] Based on what we currently know, identify holes and opportunities for further user research into priorities
- [ ] Accumulate the research (well organized tests, cropped video snippets, etc)

**Criteria for completion:**
- [ ] Prior research is organized 
- [ ] Key relevant findings are pulled out
- [ ] Opportunities for further research are identified

**Comment by nickykrause** [comment]
@onezerojeremy: You have probably told me this already, but I'm going to ask here so that I can start compiling links to things and such.

Is there a good place to start looking for the existing research? In our initial conversation about homepage planning, I recall someone saying that the existing research is a bit scattered, but perhaps that's not accurate.

Is there a folder somewhere containing a bunch of disjointed materials?
Or, will I need to search around in Google Drive to find files and pull them into a new folder?
Or, maybe it's scattered throughout GitHub? 

I found this so far: https://github.com/18F/FEC/wiki/design-research

Anything else is helpful!

**Comment by noahmanger** [comment]
@nickykrause Here's where the bulk of the research lies: Google Drive folder: [FEC > Design > User Research](https://drive.google.com/open?id=0B_D8iMs9xIXzfkotVlpYZjRmMUN0Tmo5THBiaWdwYXYxYktmcDZER2ZqcUg5UG13eUkyQmc) 

Within that, you'll find folders for the different phases of research:
- Early discovery interviews: mostly centered on data users, but covers a fairly wide range. Unfortunately, I was the one who did this, and not being a true researcher by trade, the documentation is a little lacking 😞 
- Early filer research: Focusing the experience of people who are filing with the FEC, as opposed to those looking for data
- Novice user research: Focusing on novice users of the campaign finance data

You'll also find a couple drafts of personas in there as well. 

Happy to go through these with you and/or @onezerojeremy at some point, but hopefully this can get you started!

**Comment by nickykrause** [comment]
@noahmanger thank you! this is great! I will look through it

(And I'm sure the discovery documentation will be just fine! :smile: )

**Comment by nickykrause** [comment]
@noahmanger, @onezerojeremy, @emileighoutlaw, @jenniferthibault   
 
I realized that I should probably update this issue. 

First thing to note: I haven't exactly followed the completion criteria that Noah outlined. We can discuss that. The sub-tasks outlined as completion criteria are themselves quite large. For example, there is really a lot of research sitting in the Google Drive folder, so the task of "organizing" the prior research is pretty monstrous. I started doing this (see [this spreadsheet](https://docs.google.com/spreadsheets/d/1LCADPfVTkO5h-oVRN4FZtnF8FpqrMSvTswHeWtd1IPE/edit#gid=0)), but I quickly became preoccupied with the task of actually reading through all the material and taking notes on it. I think I will be more able to pick up the "organization" task now that I am more informed about what is in there and what the research was actually trying to accomplish, and what the outcomes were.

...which leads me to the second thing. [This is the Google Doc](https://docs.google.com/document/d/1ab62FzX_pVwSI6RDlO6CosG5Ul-ydigcIRLp2U_kZdM/edit#) where I've been consolidating my highest-level notes about the user research I've reviewed, and what that research might mean for the home page. You are all welcome to look at it, although I am not sure it is complete, or if it is even in a useful format.

I still have to decide how to proceed from here, but I figure it's best to connect before I go much further. Happy to chat synchronously or asynchronously.

**Comment by noahmanger** [comment]
Great update! I think your move on the completion criteria makes a ton of sense. We had that in there _in order_ to get to a set of recommendations. While it's still important to do, the more important thing is the synthesis, which you did. So let's talk about how / if we want to go do those sub-tasks.

Your high-level synthesis strikes me as super strong. I think you pull out really good themes that are well supported, including several things that I know will also align with stakeholder goals. The point about needing to explain what the FEC does and what you can get at fec.gov is something they've hit on repeatedly.

And as @onezerojeremy pointed out, the point about the various audiences sharing the same tasks — and the related point about members of the same audience having different needs depending on their experience level — is spot on.

Let's talk more tomorrow!

**Comment by nickykrause** [comment]
@noahmanger thanks! 😺 

**Note to everyone:**
I never really reached a point where I felt like this write-up was "done," but I did decide that it was time to share it and get some feedback before going any further. Even if this document seems somewhat polished, I am happy to edit, add, and remove things. I stopped synthesizing and highlighting insights only because of time constraints and a desire to involve others sooner rather than later.

Also, one other quick update: Per @emileighoutlaw's excellent suggestion, I was able to connect with Ed Mullen this morning to revive some of his observations and thinking on the subject of the homepage, so we can bring that into our discussion as well. (+ the insights gained from the partners today!)

**Comment by nickykrause** [comment]
@noahmanger @onezerojeremy @emileighoutlaw @jenniferthibault 

I updated the doc a bit, mostly just filling out some of the sections with additional, relevant quotes. Admittedly, I haven't had time to read _every user interview_ in detail, but I am going to stop pushing this document, in order to to focus on other things.

If anyone has concerns about the level of completion here, feel free to voice them! I want to make sure we are in a good position for the homepage presentation, so I am open to suggestions about what else we might add. 

Otherwise, if there are no concerns, perhaps we can move this issue to "done," and we could make a separate issue for the unaddressed completion criterion, if we think it's worthwhile:

- [ ] Prior research is organized

Also, there was this item: 
- [ ] Opportunities for additional research are identified.

And I am wondering how much insight we really need on that, right now, for the homepage presentation next week. We could make it separate issue, if we think we should be working on it.

**Comment by noahmanger** [comment]
Sounds good to me.

+1 to a new issue (into the icebox) for organizing our research. I'll make that. We should do it for the FEC, but we don't need it right this moment. 

As for future research, I'd say if we feel we've got enough to go on for now, then no need to take further action. That was just there in case we found holes that we felt like needed to be explored.

**Comment by jenniferthibault** [comment]
Thanks again @nickykrause this is awesome. I'm going to give this  a fresh read tonight/tomorrow morning so that it's all recent memory for our synthesis of the home page inspiration exercise tomorrow.
