### ISSUE TITLE
Respond to press feedback on press section

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#577]
This will be complete when we've decided on an approach and addressed:
- [ ] [Italicizing court cases in press release titles](https://github.com/18F/fec-cms/issues/575)
- [x] [Boilerplate content at the bottom of press releases](https://github.com/18F/fec-cms/issues/580)
- [ ] Size of first paragraph text
- [x] Misc. typos and mis-categorized releases
- [ ] Link colors
- [ ] [Duplicate titles on pre-2016 press releases](https://github.com/18F/fec-cms/issues/573)

**Comment by emileighoutlaw** [comment]
The things we need to do for release are finished, so I'm closing this. We can open additional issues for improvements later.
